server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
#compose functions to into one function
      definition: email|sms
    stream:
      bindings:
        emailsms-out-0:
          destination: communication-sent
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
#  rabbitMq properties
#  rabbitmq:
#    host: "localhost"
#    username: "guest"
#    port: 5672
#    password: "guest"
      kafka:
        binder:
          brokers:
            -localhost:9092
