server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka"
  instance:
    prefer-ip-address: true

info:
  app:
    name: "gateway server"
    description: "API gateway server for microservice"
    version: "1.0"